---
apiVersion: v1
kind: Service
metadata:
  name: vinay
  namespace: default
  labels:
    name: vinay
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    name: vinay
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: vinay
webhooks:
  - name: vinay.phase3.com
    clientConfig:
      service:
        name: vinay
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxVENDQXBFQ0ZEeWVsWE1QQmVnT093K1VIWWRhZXVnUm1Qb0tNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1EKTVFzd0NRWURWUVFHRXdKSlRqRUxNQWtHQTFVRUNBd0NTMEV4RWpBUUJnTlZCQWNNQ1VKaGJtZGhiRzl5WlRFTwpNQXdHQTFVRUNnd0ZkbWx1WVhreERqQU1CZ05WQkFzTUJYWnBibUY1TVJvd0dBWURWUVFEREJGMmFXNWhlUzVrClpXWmhkV3gwTG5OMll6RWtNQ0lHQ1NxR1NJYjNEUUVKQVJZVmRtbHVZWGt1YXpJeU16TkFaMjFoYVd3dVkyOXQKTUI0WERUSXdNRGd4TVRFNE1qVXhOMW9YRFRJd01EZ3hOREU0TWpVeE4xb3dnWkF4Q3pBSkJnTlZCQVlUQWtsTwpNUXN3Q1FZRFZRUUlEQUpMUVRFU01CQUdBMVVFQnd3SlFtRnVaMkZzYjNKbE1RNHdEQVlEVlFRS0RBVjJhVzVoCmVURU9NQXdHQTFVRUN3d0ZkbWx1WVhreEdqQVlCZ05WQkFNTUVYWnBibUY1TG1SbFptRjFiSFF1YzNaak1TUXcKSWdZSktvWklodmNOQVFrQkZoVjJhVzVoZVM1ck1qSXpNMEJuYldGcGJDNWpiMjB3Z2dFaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNrWWdaOStESGY5K0RLMXZTamJuU05CcldEM1RPVFVkK0R0bDBBCkthQXBCaUh1QXYzOFFUbUZ0UytvZzV5Umt0T1JiTllQV2wvbW1Ka1FFTUpJMGNaaXlOd0RvRUVaWTVuZ21LKzEKYkRlVSt1VFRpMVlyVVdKVHlFRFR4MW1vTmlHTy91WFRwb3dvOXhoOGh2UnZkSzFhT25sam5Eb2pjWVNYdDFjawpsVzBLcERPRE5iNGFLZ254S0QrUyszVng1OWhwR2c4cEJEcmFyRWdoZmNJTXIzOWdlR3ZWY1UzdUdhVjl4QzNwCll2SUROY25nbnVKMUZnOU95V3VUeE9DZGR1VTduZ2hYTjJNU09BcEJ5NmtxWmZjU211MDJSWElqWmpxMks3eG4KcXJvMWx6OFFaNUt3ekEzNWwrdDhQa2FxT28zTDVIWHYyV2R4WnQzaGh2RmlLazdKQWdNQkFBRXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUlKRkZqQXRaRDh2UmJzSjhybGNydnJNMlY5NGNKZEZwYlovcU8rUWFyNmRtd1dJCkFvYWxzN0xpcTFvQTA4N1llYmpxNWdCTTBMREFoMzBob2FrVUpmK05MYmxlYVVQc2VHcjB2anhvRXB5cE12ODEKTmY0SkQrNmdYQWhqd2gxdmVvVi8yeXlkWlpCY3FYZU95NzVaY0FoNUVlL00yQlEwNkVPUFY5QzBWOUQ1ZlRXYwpyUkVrS05JeHMyQ0w2dXNNWWJtMW9OM040V3FoL2J6Q0xYMXdZZXRtZ0UwMm5BQ0wvai93ZVBIZ1F1dXcycFdWCk96dFBRWVdncXJlZGkvSHpmUERKVVVsMUp2aTh0MVZaZ3dqbXVsRWhwUmZCaStJK3BZeXRIYXg1SktnWGhoSWkKbWxhN3dvSGtyWmJ5T05aRXNxYXdTVEtuRjVyNXJ0ckpVYmVXVG5NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "pods/log"]
        operations: ["CONNECT", "CREATE", "DELETE", "UPDATE"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        apiVersions: ["v1"]
        operations: ["CONNECT", "CREATE", "DELETE", "UPDATE"]
    failurePolicy: Ignore
