---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: default
  labels:
    app: node
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: node
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: node
webhooks:
  - name: node.default.svc
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: node
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW84Q0ZIOStrR2lHbVVlK2JBbzZJSUM2ZzdRRk1teW1NQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1AKTVFzd0NRWURWUVFHRXdKSlRqRUxNQWtHQTFVRUNBd0NTMEV4RWpBUUJnTlZCQWNNQ1VKaGJtZGhiRzl5WlRFTwpNQXdHQTFVRUNnd0ZWbWx1WVhreERqQU1CZ05WQkFzTUJWWnBibUY1TVJrd0Z3WURWUVFEREJCdWIyUmxMbVJsClptRjFiSFF1YzNaak1TUXdJZ1lKS29aSWh2Y05BUWtCRmhWMmFXNWhlUzVyTWpJek0wQm5iV0ZwYkM1amIyMHcKSGhjTk1qQXdPREUwTVRFeU9UVXhXaGNOTWpFd09ERTBNVEV5T1RVeFdqQ0JqekVMTUFrR0ExVUVCaE1DU1U0eApDekFKQmdOVkJBZ01Ba3RCTVJJd0VBWURWUVFIREFsQ1lXNW5ZV3h2Y21VeERqQU1CZ05WQkFvTUJWWnBibUY1Ck1RNHdEQVlEVlFRTERBVldhVzVoZVRFWk1CY0dBMVVFQXd3UWJtOWtaUzVrWldaaGRXeDBMbk4yWXpFa01DSUcKQ1NxR1NJYjNEUUVKQVJZVmRtbHVZWGt1YXpJeU16TkFaMjFoYVd3dVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2RDltcHVUejBEb3hBTUdpdTNESndHZHZiNFJyY05FM0tIc2hRWVVOCkp6TENTeFRkMXV5VEo3SUxuck1yZjdSblp6K3BxbXJtUmFOcnJIZFF2WFZhTERtK2FHWFFJV2dGQmUzRnJmZnEKS0ViN0lQeXFKM3NDeGtxS0NOemlRVTBMdWZFQ1FOdnRPc1M3aGI5djFYM2c1eTBIenJVR09kWnlWU1JBKzk3bwpBWXRDVVFQb2ZxOFFjVGFFV1QzbW5zOU5qSnIzQ25HV3FqTGpKamFycDNmQzBQNFJQdHY5TnZlODA1UitORTJ2CldSWThaVklRVnJXOS9BYzVpUFJCMnBBZytpQlN2bWxQUVMxVEloaWhlMTlkQkc3L1JtNjR0QStvOER0Mm55RWoKRis0TXQvOGFiMEVlcTczZVZJNzV4ZHY2ZEY1WUpmemQxSUZYRGxMTFNVOXh0d0lEQVFBQk1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNNZ1NVc2lPT2UxOGxqVENEUVdoWmxZc2loY0JFSkJtYTE5MjZFMEJERDFQZ1VnRGJFCnp1ajhQVFlSQmxKaXgyTUNrWHh5VVZ2VnRVc1ZtUTF0UWx1NXFkQ2NLNjdZWkJpMkVJNDJHYmo4UHEycTVzeVcKUm9UaWZ6RlhnWGRIOEU3M0JucVZzbDF0N1hkanVMSVhVbTE5T29mU0RBWjdONThXU0hoOCtDUW5vSzQrbjFvMwpoRFBaM0FsZCtneWNTYmt6UEh4RUZIKzdTQ3Q5UC9zWXZJRVBPNDExUExJcnRwSk4wVE9HWEV2ejVUem8wMjA4Cklhei9nT3NBZDFRK3FTVWcwQWIxUkQvNWlkcUJKTDZramdCSVBRRUMxOWVBSHJVRDd6OEl5Q3dCcSsxeEJUT1MKWTZKOEVEZ1JZM2tIRXFsbzlpU2g0cVBjcDJrYW1Ganp0d25kCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments", "pods/*"]
        scope: "Namespaced"
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
